version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: unigo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: unigo_db
    volumes:
      - unigo_pg_data:/var/lib/postgresql/data

volumes:
  unigo_pg_data: